### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by juliengk**

### CODE REVIEW

**Comment by btotharye** [comment]
Can you please explain what this PR is for?

**Comment by juliengk** [comment]
* ENV ENV is specified twice
* there was a couple of duplicate packages in the list (automake, jq).
* `cd /usr/local/bin`, no action is taken in that directory.
* `mkdir /opt/mycroft` then `git clone ... /opt/mycroft`. The `git clone` command creates the directory. There is no need to create it before.
* ADD VS COPY (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy)

**Comment by btotharye** [comment]
Ok I'll have to see why this is failing in travis are you sure this built on your end successfully?

**Comment by juliengk** [comment]
yes, I built it successfully. Here is what seems to be the prob https://travis-ci.org/MycroftAI/docker-mycroft/builds/363470489#L1904

**Comment by juliengk** [comment]
I just built it again and it runs with success.

**Comment by juliengk** [comment]
Travis is all green now

**Pull request merged**
